defaults: &defaults
  app_name: "Seearm"
  foot_html: "&copy; Seearm.com"
  domain: "127.0.0.1:3000"
  admin_emails:
    - "hanhor.wu@gmail.com"
    - "tenpads@gmail.com"

  upload_url: "http://ruby-china-files-dev.b0.upaiyun.com"
  upyun_username: "test"
  upyun_password: "123123"
  upyun_bucket: "ruby-china-files-dev"
  email_server: "smtp.google.com"
  email_sender: 'dev-test@seearm.com'
  email_password: 'test123456'
  weibo: "ruby_china"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
