defaults: &defaults
  app_name: "See"
  site_name: "see app"
  site_keywords: "see app demo, see app download, ruby on rails"
  site_desc: "see app is on open source web app build with ruby on rails"
  foot_html: "&copy; xrangers.com"
  domain: "127.0.0.1:3000"
  admin_emails:
    - "hanhor.wu@gmail.com"
    - "xxx@gmail.com"

  upload_url: "http://ruby-china-files-dev.b0.upaiyun.com"
  upyun_username: "test"
  upyun_password: "123123"
  upyun_bucket: "ruby-china-files-dev"
  email_server: "smtp.google.com"
  email_sender: 'dev-test@xrangers.com'
  email_password: 'test123456'
  weibo: "http://weibo.com/xrangers"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults