#= require jquery
#= require jquery_ujs
#= require twitter/bootstrap/transition
#= require twitter/bootstrap/alert
#= require twitter/bootstrap/modal
#= require twitter/bootstrap/dropdown
#= require twitter/bootstrap/tab
#= require twitter/bootstrap/tooltip
#= require twitter/bootstrap/button
#= require will_paginate
#= require kindeditor
#= require_self